### ISSUE TITLE
How to load Events 

### ISSUE THREAD

**Issue by BenArfanour** [Xipotera/fullCalendarBundle#1]
I've installed this bundle , and the calendar was displayed but i can't see any event on it

**Comment by Xipotera** [comment]
Actually is not possible to create event by the calendar. Too more works in my job and no time to finalise this. But i'm working on this 😉
Have you trying for testdirectly add on the database yours events.

**Comment by Xipotera** [comment]
SQL sample for insert :
```sql
INSERT INTO `calendarevents` (`id`, `title`, `url`, `bgColor`, `cssClass`, `startDatetime`, `endDatetime`, `allDay`) VALUES
(1, 'Laboriosam.', NULL, '#26fde7', NULL, '2017-04-13 00:00:00', '2017-04-14 00:00:00', 1),
(5, 'Magnam vel aut eum.', NULL, '#5666e1', NULL, '2017-04-16 12:55:12', '2017-04-16 17:09:10', 0);
```

**Comment by BenArfanour** [comment]
Thanks a lot :) it works now
